script: gulp test
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - nvm install 6
  - nvm use 6
  - npm install -g gulp
  - npm install
